[package]
name = "relay-escrow"
version = "0.1.0"
description = "Utility for safely executing arbitrary instructions"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "relay_escrow"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
solana-program = "1.16"
sha2 = "0.10"